---
hostname: '{{ inventory_hostname }}'

username: susu

target_ip : 192.168.1.120

############
# packages
############

extra_packages:
  - sshpass
  - neofetch
  - git
  - nano 
  - vim
  - htop
  - cifs-utils
  - python3-requests

############
# docker
############

docker_dir: /docker/config
docker_compose_dir: /docker/compose

############
# smb share
############

# smb_share: //192.168.1.30/Tristan/mac-mini
# smb_mount: /mnt/prox-media