---
hostname: '{{ inventory_hostname }}'

username: susu

############
# packages
############

extra_packages:
  - sshpass
  - neofetch
  - git
  - nano 
  - vim
  - htop
  - cifs-utils
  - python3-requests

############
# docker
############

docker_dir: /docker/config
docker_compose_dir: /docker/compose
