---
# - name: Mount network share
#   mount:
#     src: "{{ smb_share }}"
#     path: "{{ smb_mount }}"
#     fstype: cifs
#     opts: 'uid={{ smb_uid }},gid={{ smb_pid }},rw'
#     state: mounted
#   become: true

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    group: "docker"
    owner: "{{ username }}"
    mode: "755"
  loop:
    - "{{ media_dir }}"
    - "{{ docker_compose_dir }}/media"
    
- name: Copy the compose file
  template: 
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/media/compose.yaml"

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}/media"
    pull: always

# - name: Docker prune
#   community.general.docker_prune:
#     networks: yes
#     images: yes
