---
- name: Create the folders
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
    state: directory
  loop:
    - "{{ swarm.docker_dir }}"
    - "{{ swarm.docker_dir }}/compose"

- name: Copy the compose files
  template: 
    src: "templates/{{ item.name }}.yaml"
    dest: "{{ swarm.docker_dir }}/compose/{{ item.name }}.yaml"
  loop: "{{ swarm.stacks }}"

- name: Create networks
  docker_network:
    name: "{{ item }}"
    driver: overlay
    scope: swarm
    attachable: true
  loop: "{{ swarm.docker_networks }}"
  when: swarm.docker_networks is defined

- name: Configuration for stacks
  include_tasks: stacks-config.yaml
  loop: "{{ swarm.stacks }}"
  loop_control:
    loop_var: stack

- name: Deploy stacks
  docker_stack:
    state: present
    name: "{{ item.name }}"
    compose:
      - "{{ swarm.docker_dir }}/compose/{{ item.name }}.yaml"
  loop: "{{ swarm.stacks }}"
