---
- name: Create folders
  ansible.builtin.file:
    path: "{{ gluster.mount_dir }}/swarm/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop: "{{ stack.volumes }}"
  when: stack.volumes is defined
  become: false

- name: Create volumes
  docker_volume:
    driver: "{{ gluster.gluster_alias }}"
    name: "{{ gluster.volume_name }}/swarm/{{ item }}"
  loop: "{{ stack.volumes }}"
  when: stack.volumes is defined

- name: Copy config file {{ stack.config }} for stack {{ stack.name }}
  template:
    src: "templates/config/{{ item.file }}"
    dest: "{{ gluster.mount_dir }}/swarm/{{ item.dst }}"
    force: "{{ item.force | default(true) }}"
  loop: "{{ stack.config }}"
  when: stack.config is defined
