---
- name: Check if volume directories exist
  ansible.builtin.stat:
    path: "{{ gluster.mount_dir }}/swarm/{{ item }}"
  loop: "{{ stack.volumes }}"
  register: volume_stats

- name: Create folder if it doesn't exist
  ansible.builtin.file:
    path: "{{ gluster.mount_dir }}/swarm/{{ item.item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop: "{{ volume_stats.results }}"
  when: not item.stat.exists
  become: false

- name: Create volumes
  docker_volume:
    driver: "{{ gluster.gluster_alias }}"
    name: "{{ gluster.volume_name }}/swarm/{{ item }}"
  loop: "{{ stack.volumes }}"
  when: stack.volumes is defined

- name: Copy config files for the stack 
  template:
    src: "templates/config/{{ item.file }}"
    dest: "{{ gluster.mount_dir }}/swarm/{{ item.dst }}"
    force: "{{ item.force | default(true) }}"
  loop: "{{ stack.config }}"
  when: stack.config is defined
