services:

#
#  System Services
#

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_dir}}/portainer/data:/data"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "81:80/tcp"
    environment:
      - TZ=Etc/UTC
      - WEBPASSWORD={{ pihole_webpassword }}
    volumes:
      - "{{ docker_dir}}/pihole:/etc/pihole"
      - "{{ docker_dir}}/pihole/dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped


#
#  Network
#
