services:

#
#  System Services
#

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_dir}}/portainer/data:/data"
    networks:
      - Dashboard
      
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_dir}}/homaarr/config:/app/data/configs"
      - "{{ docker_dir}}/homaarr/icons:/app/public/icons"
      - "{{ docker_dir}}/homaarr/data:/data"
    ports:
      - 80:7575
    networks:
      - Dashboard

  twingate:
    image: twingate/connector:1
    container_name: "{{ twingate_container_name }}"
    restart: always
    environment:
      - TWINGATE_NETWORK={{ twingate_network }}
      - TWINGATE_ACCESS_TOKEN={{ twingate_access_token }}
      - TWINGATE_REFRESH_TOKEN={{ twingate_refresh_token }}
      - TWINGATE_LABEL_HOSTNAME=`hostname`
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    networks:
      - Dashboard

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     - "54:53/tcp"
  #     - "54:53/udp"
  #     - "81:80/tcp"
  #   environment:
  #     - TZ=Etc/UTC
  #     - WEBPASSWORD={{ pihole_webpassword }}
  #   volumes:
  #     - "{{ docker_dir}}/pihole:/etc/pihole"
  #     - "{{ docker_dir}}/pihole/dnsmasq.d:/etc/dnsmasq.d"
  #   restart: unless-stopped
  #   networks:
  #     - Dashboard

#
#  Network
#

networks:
  Dashboard:
