---

- name: Get node role in cluster
  shell: "docker node inspect self --format '{{ \"{{.Spec.Role}}\" }}'"
  register: swarm_status
  failed_when: false
  changed_when: false

- name: Set fact node role
  set_fact:
    is_manager: "{{ swarm_status.stdout == 'manager' }}"
    is_worker: "{{ 'Worker nodes' in swarm_status.stderr }}"
    is_not_in_swarm: "{{ 'docker swarm join' in swarm_status.stderr }}"
  when: "'Workers' in group_names or 'Managers' in group_names"


- include_tasks: leader.yml
  when: "'Leader' in group_names"

- include_tasks: manager.yml
  when: "'Managers' in group_names"

- include_tasks: worker.yml
  when: "'Workers' in group_names"