---
- name: Join cluster as worker
  shell: "docker swarm join --token {{ hostvars[groups['Leader'][0]].join_command_worker }} {{ groups['Leader'][0] }}:2377"
  when:
    - "'Workers' in group_names"
    - "is_not_in_swarm"

- name: Join cluster as manager
  shell: "docker swarm join --token {{ hostvars[groups['Leader'][0]].join_command_manager }} {{ groups['Leader'][0] }}:2377"
  when:
    - "'Managers' in group_names"
    - "is_not_in_swarm"
