services:

#
#  Media Services 
#

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - "{{ docker_dir }}/jellyfin/config:/config"
      - "{{ docker_dir }}/jellyfin/cache:/cache"
      - "{{ media_dir }}:/media"
    restart: unless-stopped
    networks:
      - MediaNetwork

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - "{{ docker_dir }}/prowlarr/config:/config"
    ports:
      - 9696:9696
    networks:
      - MediaNetwork
    restart: unless-stopped

  jellyseer: 
    container_name: jellyseer
    image: fallenbagel/jellyseerr:latest 
    restart: unless-stopped
    ports:
      - 5055:5055
    volumes:
      - "{{ docker_dir }}/jellyseer/config:/app/config"
    labels:
      traefik.enable: true
      traefik.http.routers.request.entryPoints: https
    networks:
      - MediaNetwork
      
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1001
    volumes:
      - "{{ docker_dir }}/sonarr/data:/config"
      - "{{ media_dir }}/downloads:/downloads"
      - "{{ media_dir }}/tvseries:/tv"
    ports:
      - 8989:8989
    networks:
      - MediaNetwork
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - "{{ docker_dir }}/radarr/config:/config"
      - "{{ media_dir }}/downloads:/downloads"
      - "{{ media_dir }}/movies:/movies"
    ports:
      - 7878:7878
    networks:
      - MediaNetwork
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "{{ docker_dir }}/bazarr/config:/config"
      - "{{ media_dir }}/movies:/movies"
      - "{{ media_dir }}/tvseries:/tv"    
    ports:
      - 6767:6767
    restart: unless-stopped
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - "{{ docker_dir }}/qbit/appdata/config:/config"
      - "{{ media_dir }}/downloads:/downloads"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - MediaNetwork
    restart: unless-stopped

#
#  Network
#

networks:
  MediaNetwork:
