services:

#
#  System Services
#

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_dir}}/portainer/data:/data"
    networks:
      - Dashboard
      
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_dir}}/homaarr/config:/app/data/configs"
      - "{{ docker_dir}}/homaarr/icons:/app/public/icons"
      - "{{ docker_dir}}/homaarr/data:/data"
    ports:
      - 80:7575
    networks:
      - Dashboard

#
#  Media Services
#

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - "{{ docker_dir}}/jellyfin/config:/config"
      - "{{ docker_dir}}/jellyfin/cache:/cache"
      - "{{ docker_dir}}/media:/media"
    restart: 'unless-stopped'
    networks:
      - Dashboard
      - MediaNetwork
    devices:
      - "/dev/dri:/dev/dri" 

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "{{ docker_dir}}/prowlarr/config:/config"
    ports:
      - 9696:9696
    networks:
      - Dashboard
      - MediaNetwork
    restart: unless-stopped

  jellyseer: 
    container_name: jellyseer
    image: fallenbagel/jellyseerr:latest 
    restart: unless-stopped
    ports:
      - 5055:5055
    volumes:
      - "{{ docker_dir}}/jellyseer/config:/app/config"
    labels:
      traefik.enable: true
      traefik.http.routers.request.entryPoints: https
    networks:
      - Dashboard
      - MediaNetwork
      
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "{{docker_dir}}/sonarr/data:/config"
      - "{{docker_dir}}/media/downloads:/downloads"
      - "{{docker_dir}}/media/tvseries:/tv"
    ports:
      - 8989:8989
    networks:
      - Dashboard
      - MediaNetwork
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "{{docker_dir}}/radarr/config:/config"
      - "{{docker_dir}}/media/downloads:/downloads"
      - "{{docker_dir}}/media/movies:/movies"
    ports:
      - 7878:7878
    networks:
      - Dashboard
      - MediaNetwork
    restart: unless-stopped
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - "{{ docker_dir}}/qbit/appdata/config:/config"
      - "{{ docker_dir}}/media/downloads:/downloads"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - Dashboard
      - MediaNetwork
    restart: unless-stopped

#
#  Network
#

networks:
  MediaNetwork:
  Dashboard:
