---
- hosts: all 
  gather_facts: false
  become: yes

  roles: 
    - role: system
      tags: 
        - System

    - role: docker
      tags: 
        - Docker

- hosts: Dionysos
  roles: 
    - role: mediaServices
      tags: 
        - MediaServices

- hosts: Hermes
  roles: 
    - role: networkServices 
      tags: 
        - NetworkServices

- hosts: Vulcan
  roles: 
    - role: utilsServices
      tags: 
        - UtilsServices