services:

  urbackup:
    image: uroni/urbackup-server:2.5.x
    restart: always
    ports:
      - "{{ services_ip }}:55413:55413"
      - "{{ services_ip }}:55415:55415"
    networks:
      - proxy_network
      - backup
    environment:
      - PUID={{ docker.puid }}
      - PGID={{ docker.pgid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker.docker_dir }}/volumes/urbackup/db:/var/urbackup"
      - "{{ docker.docker_dir }}/backups:/backups"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.urbackup.loadbalancer.server.port=55414"
      - "traefik.http.routers.urbackup.rule=Host(`backup.{{ docker.domain }}`)"
      - "traefik.http.routers.urbackup.entrypoints=websecure"

  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.35.0
    restart: unless-stopped
    environment:
      - "TZ={{ timezone }}"
      - "BASE_URL=https://zerobyte.{{ docker.domain }}"
      - "APP_SECRET={{ zerobyte.app_secret }}" 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker.docker_dir }}/volumes/zerobyte:/var/lib/zerobyte"
      - "{{ docker.docker_dir }}:/data:ro"
      - "{{ nas.mount }}/volumes/zerobyte:/backups"
    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.zerobyte.loadbalancer.server.port=4096"
      - "traefik.http.routers.zerobyte.rule=Host(`zerobyte.{{ docker.domain }}`)"
      - "traefik.http.routers.zerobyte.entrypoints=websecure"

  # rustfs:
  #   image: rustfs/rustfs:latest
  #   restart: unless-stopped
  #   user: "{{ nas.puid }}:{{ nas.pgid }}"
  #   security_opt:
  #     - "no-new-privileges:true"
  #   environment:
  #     - RUSTFS_VOLUMES=/data/rustfs0
  #     - RUSTFS_ADDRESS=0.0.0.0:9000
  #     - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
  #     - RUSTFS_CONSOLE_ENABLE=true
  #     - RUSTFS_CORS_ALLOWED_ORIGINS=*
  #     - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
  #     - RUSTFS_ACCESS_KEY={{ rustfs.access_key }}
  #     - RUSTFS_SECRET_KEY={{ rustfs.secret_key }}
  #     - RUSTFS_REGION=auto
  #     - RUSTFS_OBS_LOGGER_LEVEL=info
  #     - RUSTFS_OBS_LOG_DIRECTORY=/logs
  #     - RUSTFS_IDENTITY_OPENID_ENABLE=on
  #     - RUSTFS_IDENTITY_OPENID_CONFIG_URL=https://pocket-id.{{ docker.domain }}/.well-known/openid-configuration
  #     - RUSTFS_IDENTITY_OPENID_CLIENT_ID={{ rustfs.client_id }}
  #     - RUSTFS_IDENTITY_OPENID_CLIENT_SECRET={{ rustfs.client_secret }}
  #     - RUSTFS_IDENTITY_OPENID_SCOPES=openid,profile,email
  #     - RUSTFS_IDENTITY_OPENID_GROUPS_CLAIM=groups
  #     - RUSTFS_IDENTITY_OPENID_ROLES_CLAIM=roles
  #   volumes:
  #     - "{{ nas.mount }}/volumes/rustfs/data:/data"
  #     - "{{ docker.docker_dir }}/volumes/rustfs/logs:/logs"
  #   networks:
  #     - proxy_network
  #   labels:
  #     - "traefik.enable=true"
  #     # RustFS UI
  #     - "traefik.http.services.rustfs-ui.loadbalancer.server.port=9001"
  #     - "traefik.http.routers.rustfs-ui.rule=Host(`bucket.{{ docker.domain }}`)"
  #     - "traefik.http.routers.rustfs-ui.entrypoints=websecure"
  #     - "traefik.http.routers.rustfs-ui.service=rustfs-ui"
  #
  #     - "traefik.http.services.rustfs-bucket.loadbalancer.server.port=9000"
  #     - "traefik.http.routers.rustfs-bucket.rule=Host(`s3.{{ docker.domain }}`)"
  #     - "traefik.http.routers.rustfs-bucket.entrypoints=websecure"
  #     - "traefik.http.routers.rustfs-bucket.service=rustfs-bucket"

networks:
  proxy_network:
    external: true
  backup:
