---
username: susu

swarm:
  advertise_addr: 192.168.1.111:2377

############
# packages
############

extra_packages:
  - sshpass
  - neofetch
  - git
  - nano 
  - vim
  - btop
  - cifs-utils

############
# docker
############
