---
- name: Install GlusterFS Docker Plugin
  ansible.builtin.command:
    cmd: "docker plugin install --alias {{ gluster.gluster_alias }} \ 
          trajano/glusterfs-volume-plugin:v2.0.3 
          \ --grant-all-permissions --disable"

- name: Set SERVERS for GlusterFS Docker Plugin
  community.docker.docker_plugin:
    plugin_name: "{{ gluster.gluster_alias }}"
    plugin_options:
      SERVERS: "{{ gluster_ips_reordered }}"

- name: Enable the plugin
  community.docker.docker_plugin:
    plugin_name: "{{ gluster.gluster_alias }}"
    state: enable