---
- name: Install GlusterFS
  apt:
    name: "glusterfs-server"
    state: present

- name: Activate GlusterFS service
  ansible.builtin.systemd:
    name: glusterd
    enabled: yes
    state: started

- name: Create a trusted storage pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ groups['Gluster'] | difference([inventory_hostname]) }}"
  when: 
    - "'Leader' in group_names"

- name: Create brick directory
  file:
    path: /gluster/swarm_vol
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0755'

- name: Create GlusterFS volume with multiple bricks
  gluster.gluster.gluster_volume:
    state: present
    name: swarm_vol
    bricks: "/gluster/swarm_vol"
    cluster: "{{ groups['Gluster'] | map('extract', hostvars, 'target_ip') | list }}"
    replicas: 3
    force: true
  run_once: true

- name: Start GlusterFS volume
  gluster.gluster.gluster_volume:
    state: started
    name: swarm_vol

- name: Mount GlusterFS volume
  ansible.posix.mount:
    path: /mnt/glusterfs
    src: "{{ groups['Gluster'][0] }}:/swarm_vol"
    fstype: glusterfs
    opts: defaults,_netdev
    state: mounted

- name: Install GlusterFS Docker Plugin
  community.docker.docker_plugin:
    plugin_name: trajano/glusterfs-volume-plugin:v2.0.3
    alias: glusterfs
    state: disable

- name: Get sorted list of Gluster node IPs
  set_fact:
    gluster_ips_sorted: "{{ groups['Gluster'] | map('extract', hostvars, 'target_ip') | list | unique | sort }}"

- name: Get index of current node in sorted list
  set_fact:
    gluster_self_index: "{{ gluster_ips_sorted.index(hostvars[inventory_hostname]['target_ip'] | string) | int }}"

- name: Reorder Gluster node list (starting from current node)
  set_fact:
    gluster_ips_reordered: "{{ (gluster_ips_sorted[gluster_self_index | int :] + gluster_ips_sorted[:gluster_self_index | int]) | join(',') }}"

- name: Set SERVERS for GlusterFS Docker Plugin
  community.docker.docker_plugin:
    plugin_name: glusterfs
    plugin_options:
      SERVERS: "{{ gluster_ips_reordered }}"

- name: Enable the plugin
  community.docker.docker_plugin:
    plugin_name: glusterfs
    state: enable