---
- name: Configure Proxmox host and provision VMs and LXC containers 
  hosts: proxmox
  become: true
  gather_facts: false

  vars:
    ubuntu_cloudimg_filename: "{{ (ubuntu_lts_image_url | regex_replace('.*/', '')) | default('noble-server-cloudimg-amd64.img') }}"

  pre_tasks:
    - name: Resolve local SSH public key for cloud-init
      set_fact:
        ssh_public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      when: ssh_public_key is not defined

  tasks:
    - name: Install powertop
      package:
        name: powertop
        state: present

    - name: Autotune powertop
      ansible.builtin.command: powertop --auto-tune
      changed_when: false

    - name: Ensure ISO template directory exists
      file:
        path: /var/lib/vz/template/iso
        state: directory
        mode: '0755'

    - name: Ensure cloud-init snippets directory exists
      file:
        path: /var/lib/vz/snippets
        state: directory
        mode: '0755'

    - name: Ensure LXC template cache directory exists
      file:
        path: /var/lib/vz/template/cache
        state: directory
        mode: '0755'

    - name: Check if Ubuntu LXC template is present
      stat:
        path: "/var/lib/vz/template/cache/{{ ubuntu_lxc_template }}"
      register: lxc_template_stat

    - name: Download Ubuntu LXC template
      ansible.builtin.command: "pveam download local {{ ubuntu_lxc_template }}"
      args:
        creates: /var/lib/vz/template/cache/{{ ubuntu_lxc_template }}
      when: not lxc_template_stat.stat.exists

    - name: Check if Ubuntu cloud image is present
      stat:
        path: "/var/lib/vz/template/iso/{{ ubuntu_cloudimg_filename }}"
      register: cloudimg_stat

    - name: Download Ubuntu LTS cloud image
      get_url:
        url: "{{ ubuntu_lts_image_url }}"
        dest: "/var/lib/vz/template/iso/{{ ubuntu_cloudimg_filename }}"
        mode: '0644'
        force: true
      when: not cloudimg_stat.stat.exists

    - name: Identify unprivileged LXCs requiring iGPU passthrough
      ansible.builtin.set_fact:
        igpu_lxcs: >-
          {{ lxc_containers | default([])
             | selectattr('enable_igpu', 'equalto', true)
             | rejectattr('privileged', 'equalto', true)
             | list }}

    - name: Configure Proxmox host for iGPU LXC passthrough
      when: igpu_lxcs | length > 0
      block:
        - name: Get video group GID
          ansible.builtin.command: getent group video
          register: video_group_entry
          changed_when: false

        - name: Get render group GID
          ansible.builtin.command: getent group render
          register: render_group_entry
          changed_when: false

        - name: Set iGPU GID facts
          ansible.builtin.set_fact:
            igpu_video_gid: "{{ video_group_entry.stdout.split(':')[2] | int }}"
            igpu_render_gid: "{{ render_group_entry.stdout.split(':')[2] | int }}"

        - name: Allow root to map video group GID into unprivileged LXC
          ansible.builtin.lineinfile:
            path: /etc/subgid
            line: "root:{{ igpu_video_gid }}:1"
            regexp: "^root:{{ igpu_video_gid }}:"

        - name: Allow root to map render group GID into unprivileged LXC
          ansible.builtin.lineinfile:
            path: /etc/subgid
            line: "root:{{ igpu_render_gid }}:1"
            regexp: "^root:{{ igpu_render_gid }}:"

    - name: Provision each VM
      include_tasks: provision_vm.yaml
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
        label: "{{ vm.name }}"

    - name: Provision each LXC container
      include_tasks: provision_lxc.yaml
      loop: "{{ lxc_containers | default([]) }}"
      loop_control:
        loop_var: ct
        label: "{{ ct.hostname }}"
