---
- name: Provision VMs on Proxmox
  hosts: proxmox
  become: true
  gather_facts: false

  vars:
    ubuntu_cloudimg_filename: "{{ (ubuntu_lts_image_url | regex_replace('.*/', '')) | default('noble-server-cloudimg-amd64.img') }}"

  pre_tasks:
    - name: Resolve local SSH public key for cloud-init
      set_fact:
        ssh_public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      when: ssh_public_key is not defined

  tasks:
    - name: Ensure ISO template directory exists
      file:
        path: /var/lib/vz/template/iso
        state: directory
        mode: '0755'

    - name: Ensure cloud-init snippets directory exists
      file:
        path: /var/lib/vz/snippets
        state: directory
        mode: '0755'

    - name: Check if Ubuntu cloud image is present
      stat:
        path: "/var/lib/vz/template/iso/{{ ubuntu_cloudimg_filename }}"
      register: cloudimg_stat

    - name: Download Ubuntu LTS cloud image
      get_url:
        url: "{{ ubuntu_lts_image_url }}"
        dest: "/var/lib/vz/template/iso/{{ ubuntu_cloudimg_filename }}"
        mode: '0644'
        force: true
      when: not cloudimg_stat.stat.exists

    - name: Provision each VM
      include_tasks: provision_vm.yml
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
        label: "{{ vm.name }}"