---
- name: Set up new node 
  hosts: all
  become: true

  tasks:
    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - sudo

    - name: Add user 
      user:
        name: "{{ username }}" 
        state: present
        groups: sudo
        append: yes
        password: "{{ hash_pass }}"
        shell: /bin/bash

    - name: apt update && upgrade
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Copy the public SSH key 
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"