---
- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    group: "docker"
    owner: "{{ username }}"
    mode: "755"
  loop:
    - "{{ docker_compose_dir }}/utils"
    
- name: Copy the compose file
  template: 
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/utils/compose.yaml"

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}/utils"
    pull: always

- name: Docker prune
  community.docker.docker_prune:
    networks: yes
    images: yes
    