---
- name: install dependency
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 7777
    state: directory
  loop:
    - "{{ docker_dir }}"
    - "{{ docker_compose_dir }}"

- name: Copy the compose file
  template: 
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/compose.yaml"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
    pull: yes

# - name: Twingate container 
#   command: 
#      cmd: sudo docker run -d --env TWINGATE_NETWORK="{{ twingate_network }}" --env TWINGATE_ACCESS_TOKEN="{{ twingate_access_token }}" --env TWINGATE_REFRESH_TOKEN="{{ twingate_refresh_token }}"  --env TWINGATE_LABEL_HOSTNAME="`hostname`" --name "{{ twingate_container_name }}" --restart=unless-stopped --network="host" --pull=always twingate/connector:1
