services:

  traefik:
    image: traefik:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    command:
      - "--configFile=/letsencrypt/traefik.yaml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "gfs_traefik:/letsencrypt"
    networks:
      - proxy_network
    environment:
      - DUCKDNS_TOKEN={{ duckdns_token }}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
        - "traefik.http.routers.traefik.rule=Host(`traefik.{{ swarm.domain }}`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.service=api@internal"
  
  whoami:
    image: "traefik/whoami"
    networks:
      - proxy_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=proxy_network" 
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.rule=Host(`whoami.{{ swarm.domain }}`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.routers.whoami.entrypoints=websecure"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - gfs_homepage:/app/config 
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "homepage.{{ swarm.domain }}"
      PUID: "{{ nas.puid }}"
      PGID: "{{ nas.pgid }}"
    networks:
      - proxy_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=proxy_network" 
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"
        - "traefik.http.routers.homepage.rule=Host(`homepage.{{ swarm.domain }}`)"
        - "traefik.http.routers.homepage.entrypoints=web"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        
networks:
  proxy_network:
      external: true

volumes:
  gfs_traefik:
    driver: "{{ gluster.gluster_alias }}"
    name: "{{ gluster.volume_name }}/swarm/traefik"

  gfs_homepage:
    driver: "{{ gluster.gluster_alias }}"
    name: "{{ gluster.volume_name }}/swarm/homepage"
