---

- name: Stop the systemd-resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  become: true

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    group: "docker"
    owner: "{{ username }}"
    mode: "755"
  loop:
    - "{{ docker_compose_dir }}/network"

- name: Copy the compose file
  template: 
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/network/compose.yaml"

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}/network"
    pull: always

# - name: Docker prune
#   community.docker.docker_prune:
#     networks: yes
#     images: yes
#   timeout: 300
